---
output:
  pdf_document:
    latex_engine: xelatex

mainfont: DejaVuSerif.ttf
sansfont: DejaVuSans.ttf
monofont: DejaVuSansMono.ttf 

mainfontoptions:
- Extension=.ttf
- UprightFont=*
- BoldFont=*-Bold
- ItalicFont=*-Italic
- BoldItalicFont=*-BoldItalic

numbersections: true
indent: true

header-includes:
- \usepackage{indentfirst}
- \usepackage[russian]{babel}
---
\input{./src/title.tex}
\input{./src/extra.tex}

\begin{center} 
    {\Large Отчет студента}
\end{center}

\tableofcontents
\clearpage

# Что такое "Анализ выживаемости"? 

*Анализ выживаемости* --- набор статистических моделей, благодаря которым можно оценить вероятность наступления того или иного события.
Анализ занимается моделированием процессов наступления *интересующих* нас (критических) событий для элементов той или иной совокупности (изначально — «смерти» для элементов совокупности живых существ). 

*Интересным* событием может быть что угодно. Это может быть фактическая смерть, рождение, выход на пенсию и т. д.

Название *"survival analysis"* взято из медицины, т.к. цель анализа заключается в изучении продолжительности жизни пациента после приема препарата или других факторов влияния на здоровье. 

## Основные понятия

### Функция выживания (Survival function)

Пусть $T$ --- неотрицательная случайная величина, представляющая собой время ожидания до наступления некоторого события.
Для простоты будем использовать терминологию анализа выживаемости, называя исследуемое событие «смертью», а время ожидания – временем «выживания»

*Функция выживания* сопоставляет некоторому числу $t$ вероятность того, что случайная величина $T$ примет значение, не меньшее $t$. Иначе говоря, это вероятность того, что некоторое состояние «проживет» как минимум t единиц времени:

$$S(t) = \mathbb{P}\{T > t\} = 1 - \mathbb{P}\{T \leq t\}$$

Например, если мы хотим знать, какова вероятность того, что безработный индивид не сможет найти работу в течение полугода после начала поиска, то достаточно рассмотреть функцию выживания для $t = 6$ месяцев.

### Функция риска (Hazard function)

*Функцию риска* можно охарактеризовать как вероятность того, что событие произойдет за бесконечно малый интервал времени при условии, что оно не произошло к моменту времени $t$.

$$h(t) = \lim_{dt \to 0}\frac{\mathbb{P} (t \leq T < t + dt|T \geq t)}{dt}$$

Числитель этого выражения --- условная вероятность того, что событие произойдет в интервале $(t, t + dt)$, если оно не произошло ранее, а знаменатель --- ширина интервала. Разделив одно на другое, получаем интенсивность осуществления события в единицу времени. Устремляя ширину интервала к нулю и переходя к пределу, получаем *мгновенную интенсивность осуществления события*.

Т. к. вышесвязанные функции связаны друг с другом, можно показать, что:

$$S(t) = \exp{(-\int_{0}^{t}h(x)dx)}$$

Интеграл в фигурных скобках в этом уравнении называют *кумулятивным риском* и обозначают как:

$$H(t) = \int_{0}^{t}h(x)dx$$

Можно рассматривать $H(t)$ как сумму всех рисков при переходе от момента времени 0 к $t$.

### Цензурирование (censoring)

*Цензурирование* --- вид неполноты информации, при котором наблюдения не содержат точной длительности изучаемого состояния. Различают цензурирование справа, слева и интервальное:

1. Цензурировано справа --- о наблюдаемом состоянии известно лишь, что оно продлилось не менее определенного времени.
1. Цензурировано слева --- о состоянии известно лишь, что оно продлилось не более определенного времени.
1. На интервале --- известны только границы длительности.

### Медиана ожидаемого времени жизни (median number of survival days)

Это точка на временной оси, в которой кумулятивная функция выживания равна 0,5.

Другими словами, *медиана* --- время, выраженное в месяцах или годах, когда ожидается, что половина пациентов будет жива. Это означает, что шанс выжить после этого времени составляет 50 процентов.

### Доверительный интервал (confidence interval)

 Доверительный интервал --- интервал, который покрывает неизвестный параметр с заданной надёжностью.
 Вероятность, с которой в условиях данного эксперимента полученные экспериментальные данные можно считать надежными (достоверными), называют доверительной вероятностью или надежностью. Величина доверительной вероятности определяется характером производимых измерений. Мы будем считать доверительную вероятность равной 95 %.

### Усечение (truncation)

*Усечением*, или урезанием, называется вид неполноты информации, при котором какая-то область возможных значений длительности оказывается недостаточно представленной в выборке: состояния, длительность которых слишком велика или, наоборот, слишком мала, просто не включаются в анализируемые данные. В нашей задаче мы будем называть их (removed) --- пациенты, которые больше не являются частью нашего эксперимента. Если человек умирает или подвергается цензуре, то он попадает в эту категорию.

### Оценка Каплана --- Мейера, оценка Нельсона --- Аалена

При отсутствии цензурирования и усечения для оценивания закона распределения вероятностей может использоваться эмпирическая функция распределения, из которой легко получить оценки для других характеристик случайной величины: survival function etc. Но в нашем случае это невозможно, т. к. мы имеем дело с неполнотой данных. Эту проблему решают непараметрические методы оценки.

***Оценка Каплана --- Мейера***

*Оценка Каплана-Мейера* --- это непараметрическая статистика, используемая для оценки функции выживания на основе данных о жизни. В медицинских исследованиях он часто используется для измерения доли пациентов, живущих в течение определенного времени после лечения или постановки диагноза. Например: подсчет количества времени, которое прожил конкретный пациент после того, как у него был диагностирован рак или началось его лечение.

$$\hat{S}(t) = \prod_{t_{j} \leq t} {\frac{n_{j} - d_{j}}{n_{j}}}$$

где 

$\hat{S}(t) =$ Вероятность того, что испытуемый жив в момент времени $t$

$n_{j} =$ Количество испытуемых, оставшихся в живых непосредственно перед моментом времени $t_{j}$

$d_{j} =$ Количество событий в момент времени $t_{j}$

Можем переписать формулу выше так:

$$S(t_{j}) = S(t_{j-1})(1 - \frac{d_{j}}{n_{j}})$$

где

$S(t_{j}) =$ Вероятность того, что испытуемый жив в момент времени $t_{j}$

$n_{j} =$ Количество испытуемых, оставшихся в живых непосредственно перед моментом времени $t_{j}$

$d_{j} =$ Количество событий в момент времени $t_{j}$

$S(0) = 1$

$t_{0} = 0$

***Оценка Нельсона --- Аалена***

Мы можем визуализировать совокупную информацию о выживании, используя функцию риска *Нельсона-Аалена $h(t)$*. Функция риска $h(t)$ дает нам вероятность того, что субъект, находящийся под наблюдением в момент времени $t$, имеет интересующее событие (смерть) в это время. Чтобы получить информацию о функции опасности, мы не можем преобразовать оценку Каплана-Мейера. Для этого существует соответствующая непараметрическая оценка кумулятивной функции опасности:

$$\hat{H}(t) = \sum_{t_{j} \leq t}{\frac{d_{j}}{n_{j}}}$$

где

$\hat{H}(t) =$ Кумулятивная вероятность опасности

$n_{j} =$ Количество испытуемых, оставшихся в живых непосредственно перед моментом времени $t_{j}$

$d_{j} =$ Количество событий в момент времени $t_{j}$

## Пример решения задачи

В качестве примера для анализа выживаемости возьмем заболевание *Monkeypox*

